name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        # Use npm install because the repo doesn't commit a package-lock.json yet.
        # If you add a lockfile later, switch back to `npm ci` for reproducible installs.
        run: npm install

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpcs
          ini-values: memory_limit=256M

      - name: Install PHP CodeSniffer standards
        run: |
          composer global require "wp-coding-standards/wpcs:^3.0"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Lint JS
        run: npm run lint:js --if-present

      - name: Lint PHP
        run: npm run lint:php --if-present

      - name: Build
        run: npm run build

      - name: Generate POT (informational only)
        run: npm run pot --if-present
        continue-on-error: true
